### PR TITLE
Added support for Dynamically Injecting the 'Source' at Runtime so yo…

### PR DESCRIPTION
**Pull request by bmistry13**
1) Added Shutdown of cluster after xx interval (after data is processed) .
2) Added Ability to configure sources dynamically at runtime.
3) Added More status for java thread dump and added each source status 

Thanks,
Bhavesh

### CODE REVIEW

**Comment by nzhang1220** [comment]
Bhavesh,
(1) please remove "distributionManagement" tag in pom.xml, this is a serious issue that violates Walmart's security code.
(2) the current Mupd8 version is 2.2.9, please try to use 2.2.10 or 2.3.0.

Please re-submit your patch without any Walmart internal repository info. Have to close it now for security reasons.

**Comment by bmistry13** [comment]
I did not realize distribution tag was there. I have removed it.  I re-call the patch.  It was develop long time back, you may not need it now. 

Thanks for pointing out the distribution list (can you please remove this pool request if you can ?).  

Thanks,
Bhavesh

**Comment by nzhang1220** [comment]
I think there is no way to completely delete a pull request, as mentioned in:
http://www.quora.com/What-are-ways-to-delete-a-pull-request-on-GitHub
http://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github

So I just close it now.

**Comment by bmistry13** [comment]
I will delete the branch and I will also try to ask git hub to delete pull request.  I purpose was to contribute back not to create trouble you. I will try to contact git hub (Github support staff will delete it for you...) from your reference.  I have fixed the branch but history has it. 

Thanks for pointing this out.

Thanks,
Bhavesh

Thanks,
Bhavesh

**Pull request closed without merging**
